_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
langcode: sk
theme: postbellum
defaults:
  sender: SMTPMailSystem
  formatter: SMTPMailSystem
modules:
  swiftmailer:
    none:
      sender: swiftmailer
      formatter: swiftmailer
