_core:
  default_config_hash: FS38f8_G3S09nKLtUCOEs0IhkjQQRl3UfDJnFD7B1qY
langcode: sk
credentials_file: ''
bucket: eshop.postbellum.sk
region: eu-central-1
use_cname: false
domain_root: none
use_customhost: false
hostname: ''
domain: ''
use_path_style_endpoint: false
disable_version_sync: false
cache_control_header: ''
encryption: ''
use_https: false
ignore_cache: false
read_only: false
disable_cert_verify: false
redirect_styles_ttl: 0
root_folder: ''
public_folder: public
private_folder: ''
presigned_urls: ''
saveas: ''
torrents: ''
use_credentials_cache: false
credentials_cache_dir: ''
keymodule:
  secret_key_name: ''
  access_key_name: ''
disable_shared_config_files: true
